Extend interface device definitions
libvirt/libvirt-go-xml pull request #1
Opened 2017-01-27 10:36 UTC by vincentbernat

This is still incomplete but most of the useful things are
here. Examples are taken from libvirt samples.

2017-01-27 15:58 UTC, berrange requested changes

2017-01-27 15:58 UTC, berrange commented on domain.go
> +	Port    *uint   `xml:"port,attr"`
These shouldn't be using pointers as it makes it tedious to initialize. The style used elswhere is to have omitempty annotations.

2017-01-27 15:58 UTC, berrange commented on domain.go
> +	Queues *uint  `xml:"queues,attr"`
Again, no pointers

2017-01-27 15:58 UTC, berrange commented on domain_test.go
> +			t.Error("Bad xml:\n", string(doc), "\n does not match\n", expect, "\n")
These changes are unrelated to the rest of the commit - please put them in a separate commit and why why they're needed

2017-01-27 16:25 UTC, vincentbernat commented
I have used `omitempty` instead of pointers. I have removed the last unrelated change.

2017-01-30 11:25 UTC, berrange commented
Thanks this is merged

2017-01-30 11:25 UTC, closed without merging